# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "85cdcb910aeec8e6631fd7d983345327"
name = "shop-timer"
handle = "shop-timer"
application_url = "https://slides-authority-berry-cosmetic.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://slides-authority-berry-cosmetic.trycloudflare.com/auth/callback", "https://slides-authority-berry-cosmetic.trycloudflare.com/auth/shopify/callback", "https://slides-authority-berry-cosmetic.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
